// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIOSIds
{
        public const string achievement_achievement_5 = "CgkI3tfW-NMLEAIQBA"; // <GPGSID>
        public const string leaderboard_stickman_quest_leaderboard = "CgkI3tfW-NMLEAIQBQ"; // <GPGSID>
        public const string achievement_achivement_3 = "CgkI3tfW-NMLEAIQAg"; // <GPGSID>
        public const string achievement_achievement_1 = "CgkI3tfW-NMLEAIQAA"; // <GPGSID>
        public const string achievement_achievement_2 = "CgkI3tfW-NMLEAIQAQ"; // <GPGSID>
        public const string achievement_achievement_4 = "CgkI3tfW-NMLEAIQAw"; // <GPGSID>

}

